# ─────────────────────────────────────────────────────────────────
# CONFIGURACIÓN SQL SERVER — Registraduría de Nobsa
# ─────────────────────────────────────────────────────────────────
sqlserver.url=jdbc:sqlserver://DESKTOP-RCEI1FL\\SQLEXPRESS:1433;databaseName=Registraduria;encrypt=false;trustServerCertificate=true;
sqlserver.user=sa
sqlserver.password=Registraduria2024#

# Credenciales del administrador de la app
admin.usuario=admin
admin.password=admin123
